"""Initial migration

Revision ID: 8b9fde9cd826
Revises: 
Create Date: 2025-05-22 17:24:29.066707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9fde9cd826'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_routes',
    sa.Column('route_guid', sa.String(length=36), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('elevation_gain', sa.Float(), nullable=False),
    sa.Column('avg_grade', sa.Float(), nullable=False),
    sa.Column('left_turns', sa.Integer(), nullable=False),
    sa.Column('right_turns', sa.Integer(), nullable=False),
    sa.Column('travel_time', sa.Float(), nullable=False),
    sa.Column('source_node_id', sa.String(length=255), nullable=False),
    sa.Column('source_coordinates', sa.JSON(), nullable=False),
    sa.Column('destination_node_id', sa.String(length=255), nullable=False),
    sa.Column('destination_coordinates', sa.JSON(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_routes_route_guid'), ['route_guid'], unique=True)

    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.LargeBinary(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('route_preferences',
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('selected_generated_route_id', sa.Integer(), nullable=False),
    sa.Column('presented_routes_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['selected_generated_route_id'], ['generated_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_preferences_user_uuid'), ['user_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_preferences_user_uuid'))

    op.drop_table('route_preferences')
    op.drop_table('roles')
    op.drop_table('users')
    with op.batch_alter_table('generated_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_routes_route_guid'))

    op.drop_table('generated_routes')
    # ### end Alembic commands ###
