"""empty message

Revision ID: d405c588463a
Revises: 
Create Date: 2025-07-27 02:53:51.161575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd405c588463a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('participant_id', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('current_test_type', sa.String(length=20), nullable=False),
    sa.Column('current_condition', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_participant_id'), ['participant_id'], unique=True)

    op.create_table('roles',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_test_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=20), nullable=False),
    sa.Column('condition_number', sa.Integer(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('response_times', sa.JSON(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('inter_round_survey_completed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'test_type', 'condition_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_test_progress')
    op.drop_table('roles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_participant_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
