"""changed the tables a bit

Revision ID: dc7553e0223b
Revises: 8b9fde9cd826
Create Date: 2025-05-23 19:27:17.835284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'dc7553e0223b'
down_revision = '8b9fde9cd826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trajectory_obj', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('reward_weights', sa.JSON(), nullable=False))
        batch_op.drop_column('coordinates')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('belief', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)
        batch_op.drop_column('username')
        batch_op.drop_column('password')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('belief')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('generated_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sqlite.JSON(), nullable=False))
        batch_op.drop_column('reward_weights')
        batch_op.drop_column('trajectory_obj')

    # ### end Alembic commands ###
