"""empty message

Revision ID: e1d853b3a7e5
Revises: 
Create Date: 2025-08-01 21:25:08.543200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d853b3a7e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('participant_id', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('current_test_type', sa.String(length=20), nullable=False),
    sa.Column('current_condition', sa.Integer(), nullable=False),
    sa.Column('tabletop_condition_order', sa.JSON(), nullable=True),
    sa.Column('robot_nav_condition_order', sa.JSON(), nullable=True),
    sa.Column('current_condition_index', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_participant_id'), ['participant_id'], unique=True)

    op.create_table('inter_round_survey_responses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=20), nullable=False),
    sa.Column('condition_number', sa.Integer(), nullable=False),
    sa.Column('mental_demand', sa.Integer(), nullable=False),
    sa.Column('success_level', sa.Integer(), nullable=False),
    sa.Column('frustration_level', sa.Integer(), nullable=False),
    sa.Column('trajectory_choice_ease', sa.Integer(), nullable=False),
    sa.Column('difference_clarity', sa.Integer(), nullable=False),
    sa.Column('preference_learning', sa.Integer(), nullable=False),
    sa.Column('decision_factors', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'test_type', 'condition_number')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_test_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=20), nullable=False),
    sa.Column('condition_number', sa.Integer(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('response_times', sa.JSON(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('inter_round_survey_completed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'test_type', 'condition_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_test_progress')
    op.drop_table('roles')
    op.drop_table('inter_round_survey_responses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_participant_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
